force-app/main/default/objects/Garage__c/Garage__c.object-meta.xml
<CustomObject>
    <description>Garages for car maintenance</description>
    <label>Garage</label>
    <nameField>
        <label>Garage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Garage__c/fields/zipcode__c.field-meta.xml
<CustomField>
    <fullName>zipcode__c</fullName>
    <label>zipcode</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GarageController.cls
public with sharing class GarageController {
    
    @AuraEnabled (cacheable = true)
    public Static List<Garage__c> findGarages(String searchKey){
        String key = '%' + searchKey + '%';

        return [SELECT Id, Name, Address__c, Zipcode__c, City__c, Location__latitude__s, Location__longitude__s
                FROM Garage__c
                WHERE city__c LIKE :key
                WITH SECURITY_ENFORCED
                LIMIT 1000]; 
    }
    
}